version: '3.8'

services:
  your-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: storeproject:latest
    ports:
      - "8080:8080"


  # Security configuration
  #  keycloak:
  #    image: jboss/keycloak
  #    env_file:
  #      - .env
  #    environment:
  #      - PROXY_ADDRESS_FORWARDING=true
  #    command: ["-b", "0.0.0.0"]
  #    ports:
  #      - "8081:8081"


  
